#!/usr/bin/env bash
source source.sh

devices_list=$DEVICES_LIST

for i in $devices_list
do 
  echo "## $i:"
  main4ino_get_reports $i C | jq -r '.[].device.actors.battery.".charge"'
  echo ""
  echo ""
done

