#!/usr/bin/env bash

source source.sh
function check_equals() {
  local a=$1
  local b=$2
  if [ "$a" == "$b" ]
  then
    echo OK | highlight green ".*"
  else
    echo KO | highlight red ".*"
  fi
}
function check_fresh() {
  local timestamp=$1
  local threshold=$2
  local timestamp2=`echo "$timestamp + $threshold" | bc`
  local now_timestamp="`date '+%s'`"
  if [ $now_timestamp -gt $timestamp2 ]
  then
    echo KO | highlight red ".*"
  else
    echo OK | highlight green ".*"
  fi
}

for i in $DEVICES_LIST
do 
  echo "### Device $i ###" | highlight green ".*"
  summary_report=`main4ino_get_summary_report $i`
  aliase=`echo $summary_report | jq -r  '.settings.alias'`
  version=`echo $summary_report | jq -r  '.settings."~version"'`
  project=`echo $summary_report | jq -r  '.settings.project'`
  platform=`echo $summary_report | jq -r  '.settings.platform'`
  last_report=`main4ino_get_last_report $i | jq -r '.dbId.creation'`
  version_latest=`main4ino_get_firmwares $project $platform  | jq -r .[].version | tail -1`
  logl=`echo $summary_report | jq -r  '.settings."~logl"'`
  logo=`echo $summary_report | jq -r  '.settings."~logo"'`
  echo "Info:"
  echo "- alias          : $aliase" | highlight blue $aliase
  echo "- project        : $project"
  echo "- platform       : $platform"
  echo "- last report    : `check_fresh $last_report $FRESHNESS_THRESHOLD` (`date -d @$last_report`)"
  echo "- current version: `check_equals $version $version_latest` (current: $version / latest: $version_latest)"
  echo "Summary report:"
  echo "$summary_report" | highlight gray ".*"
  echo "Logs (log level = $logl / log options = $logo):"
  main4ino_get_logs $i 0 $LOG_LENGTH | highlight gray ".*"
  echo "###" | highlight green ".*"
  echo ""
done

