#!/usr/bin/env bash
source source.sh

devices_list="$DEVICES_LIST"
ssid1=$1
pass1=$2
ssid2=$3
pass2=$4

for i in $devices_list
do 
  echo "## $i:"
  main4ino_post_target $i settings '{"~wifissid":"'$ssid1'","~wifipass":"'$pass1'","~wifissidb":"'$ssid2'","~wifipassb":"'$pass2'"}'
  echo ""
  echo ""
done

