#!/usr/bin/env bash
source source.sh

devices_list=${1:-$DEVICES_LIST}
target=$2

for i in $devices_list
do 
  echo "## $i:"
  main4ino_post_target $i settings '{"+utarget":"'$target'"}'
  echo ""
  echo ""
done

