#!/usr/bin/env bash
source source.sh

devices_list=${1:-$DEVICES_LIST}
ssid1=$2
pass1=$3
ssid2=$4
pass2=$5

for i in $devices_list
do 
  echo "## $i:"
  main4ino_post_target $i settings '{"~wifissid":"'$ssid1'","~wifipass":"'$pass1'","~wifissidb":"'$ssid2'","~wifipassb":"'$pass2'"}'
  echo ""
  echo ""
done

