#!/usr/bin/env bash
source source.sh

devices_list=${1:-$DEVICES_LIST}
logl=$2
logo=$3

for i in $devices_list
do 
  echo "## $i:"
  main4ino_post_target $i settings '{"~logo":"'$logo'","~logl":"'$logl'"}'
  echo ""
  echo ""
done

