#!/usr/bin/env bash
source source.sh

devices_list=$DEVICES_LIST
f=$1

for i in $devices_list
do 
  echo "## $i:"
  main4ino_post_target $i propsync '{"+fstorefreq":"'$f'"}'
  echo ""
  echo ""
done

