#!/usr/bin/env expect

set timeout 2400s

spawn sbt -Dsbt.log.noformat=true -Dconfig-dir=src/main/resources/defaultconfig/ "runMain org.mauritania.main4ino.Server"

expect "started at" {
    system "./misc/benchmarks/populate"
}

puts ""
puts "Service running locally..."
puts "Login to http://localhost:8080"
puts "Use credentials: admin/password"
puts ""

sleep 240

puts "Closing..."

