#!/usr/bin/env bash

set -e
set -x
set -u

root_dir=$(readlink -e `dirname $0`/../..)
config_dir=${$1:-$root_dir/../config/}

function context() {

  whoami
  date
}
function killem() {
  local pids=$1
  if [ -n "$pids" ]
  then
    echo "Killing (and force killing) existent app (if any)..."
    echo "$pids"
    kill $pids
    sleep 5
    kill -9 $pids
  fi
}

cd $root_dir

# Some logs
context

old_pids=`jps -l | grep org.mauritania.main4ino.Server | cut -d' ' -f1` 

tmp_dir=`mktemp -d`
sbt clean test
sbt universal:packageBin
find -name main4ino-server*.zip | xargs -I% unzip % -d $tmp_dir

executable=`find $tmp_dir -name main4ino-server -type f` 

nohup bash $executable -Dconfig-dir=$config_dir -Dlog4j.configuration=file://$config_dir/custom-log4j.properties &> /dev/null &

killem "$old_pids"
