#!/usr/bin/env bash

set -e
set -x
set -u

root_dir=$(readlink -e `dirname $0`/../..)
config_dir=${1:-$root_dir/../config/}
ports_list=${2:-"8090 8091 8092"}

function print_context() {
  whoami
  date
  hostname
  jps -l
}

function is_port_free() {
  local port="$1"
  if nc -z 127.0.0.1 $port
  then
    echo "false"
  else
    echo "true"
  fi
}

function find_free_port() {
  local ports_list="$1"
  local first_free=""
  for port in $ports_list
  do
    if nc -z 127.0.0.1 $port
    then
      echo ""
    else
      if [ -z "$first_free" ]
      then
        first_free=$port
      fi
    fi
  done
  echo "$first_free"
}

function killem() {
  local pids="$1"
  if [ -n "$pids" ]
  then
    echo "Context for Killing existent apps: $pids"
    jps -l
    echo "Killing existent apps: $pids"
    kill $pids
    sleep 5
    echo "Force killing existent apps: $pids"
    set +e
    kill -9 $pids
    set -e
  fi
}

function build_package() {
  sbt clean test
  sbt universal:packageBin
}

function launch_instance() {
  local port="$1"
  local old_pids="$2"
  local stdout_logs="$3"
  local stderr_logs="$4"

  local tmp_dir=$(mktemp -d)

  echo "Temporary unzipped directory: $tmp_dir"

  find -name main4ino-server*.zip | xargs -I% unzip % -d $tmp_dir

  executable=$(find $tmp_dir -name main4ino-server -type f)

  echo "Temporary logs file: $tmp_logs"

  killem "$old_pids" # must kill before the new one starts (or two processes using same DB !!!)

  /usr/sbin/daemonize -E BUILD_ID=dontKillMe \
    /bin/bash "$executable" \
    -Dserver.port="$port" \
    -Dconfig-dir="$config_dir" \
    -Dlog4j.configuration="file://$config_dir/custom-log4j.properties" -o "$stdout_logs" -e "$stderr_logs" &

}

cd $root_dir

print_context

old_pids=$(jps -l | grep org.mauritania.main4ino.Server | cut -d' ' -f1)

build_package

target_port=$(find_free_port "$ports_list")


tmp_stdout_logs=$(mktemp)
tmp_stderr_logs=$(mktemp)

launch_instance "$target_port" "$old_pids" "$tmp_stdout_logs" "$tmp_stderr_logs"

sleep 30

print_context

if [ "$(is_port_free $target_port)" == "false" ]
then
  echo "OK. The process is running (port $target_port taken)."
  cat "$tmp_logs"
  exit 0
else
  echo "KO. The process is not running (port $target_port not taken)."
  echo "STDOUT:"
  cat "$tmp_stdout_logs"
  echo "STDERR:"
  cat "$tmp_stderr_logs"
  exit 1
fi

