#!/usr/bin/env bash

set -e
set -x
set -u

root_dir=$(readlink -e `dirname $0`/../..)
config_dir=${1:-$root_dir/../config/}

function print_context() {

  whoami
  date
}
function killem() {
  local pids="$1"
  if [ -n "$pids" ]
  then
    echo "Killing existent apps: $pids"
    kill $pids
    sleep 5
    echo "Force killing existent apps: $pids"
    set +e
    kill -9 $pids
    set -e
  fi
}

cd $root_dir

print_context

old_pids=`jps -l | grep org.mauritania.main4ino.Server | cut -d' ' -f1` 

tmp_dir=`mktemp -d`
tmp_logs=`mktemp`
#sbt clean test
sbt clean universal:packageBin
find -name main4ino-server*.zip | xargs -I% unzip % -d $tmp_dir

executable=`find $tmp_dir -name main4ino-server -type f` 

/usr/sbin/daemonize -E BUILD_ID=dontKillMe /bin/bash $executable -Dconfig-dir=$config_dir -Dlog4j.configuration=file://$config_dir/custom-log4j.properties &> $tmp_logs &

killem "$old_pids"
