#!/usr/bin/env bash

# Launch me from root-directory

set -e -x

curr_dir=$(readlink -e `dirname $0`/..)
config_dir=`readlink -e $1`

cd $curr_dir
sbt "runMain org.mauritania.main4ino.Server $config_dir" 


