#!/usr/bin/env bash

# Launch me from root-directory

set -e -x

root_dir=$(readlink -e `dirname $0`/../..)

branch=stable
cd $root_dir
git checkout $branch
git reset --hard HEAD~200 # in unlikely case of history rewritting 
git pull origin $branch
git log | head -10



