#!/usr/bin/env bash

# Launch me from root-directory

set -e -x

root_dir=$(readlink -e `dirname $0`/../..)

cd $root_dir
git reset --hard HEAD~200 # in unlikely case of history rewritting 
git pull origin master
git log | head -10



