#!/usr/bin/env bash
currdir=$(pwd)
cd ../../..
sbt "runMain org.mauritania.main4ino.cli.Client $currdir/input.conf $currdir/add.conf $currdir/security.conf"
echo "File generated here: $currdir/security.conf"
