#!/usr/bin/env bash
currdir=$(readlink -e $(dirname $0))
cd $currdir/../../../
sbt -Dinput=$currdir/input.conf -Dmodif=$currdir/add.conf -Doutput=$currdir/security.conf "runMain org.mauritania.main4ino.security.confgen.Client"
cd $currdir
