#!/usr/bin/env bash
currdir=$(pwd)
cd main4ino-server
sbt -Dinput=$currdir/input.conf -Dmodif=$currdir/add.conf -Doutput=$currdir/security.conf "runMain org.mauritania.main4ino.security.confgen.Client"
