#!/usr/bin/env bash

set -x 
set -e 

curr_dir=`readlink -e $(dirname $0)`
root_dir=$curr_dir/../..

cd $root_dir

sbt "runMain org.mauritania.main4ino.security.confgen.Client $curr_dir/input.conf $curr_dir/add.conf $curr_dir/security.conf"
